// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace USync.Infrastructure.Data.ApplicationDB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("USync.Domain.Entities.Profile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastUserAlteration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUserAlterationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ProfileRuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileRuleId");

                    b.ToTable("Profile", (string)null);
                });

            modelBuilder.Entity("USync.Domain.Entities.ProfileRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastUserAlteration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUserAlterationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileRules", (string)null);
                });

            modelBuilder.Entity("USync.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUserAlteration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUserAlterationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("USync.Domain.Entities.Profile", b =>
                {
                    b.HasOne("USync.Domain.Entities.ProfileRule", "ProfileRule")
                        .WithMany()
                        .HasForeignKey("ProfileRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfileRule");
                });

            modelBuilder.Entity("USync.Domain.Entities.ProfileRule", b =>
                {
                    b.HasOne("USync.Domain.Entities.Profile", null)
                        .WithMany("ProfileRulesList")
                        .HasForeignKey("ProfileId");
                });

            modelBuilder.Entity("USync.Domain.Entities.User", b =>
                {
                    b.HasOne("USync.Domain.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("USync.Domain.Entities.Profile", b =>
                {
                    b.Navigation("ProfileRulesList");
                });
#pragma warning restore 612, 618
        }
    }
}
